leia = input('Digite algo: ')
print('O tipo primitivo do valor é: ', type(leia))
print('Só tem espaços? ', leia.isspace())
print('É um número? ', leia.isnumeric())
print('É alfabético? ', leia.isalpha())
print('É alfanumérico? ', leia.isalnum())
print('Está em maiúsculas? ',leia.isupper())
print('Está em minúscilas? ', leia.islower())
print('Está capitalizado? ', leia.istitle())